<?xml version="1.0" encoding="utf-8"?>
<Project>
  <PropertyGroup>
    <VcpkgManifestRoot>$(MSBuildThisFileDirectory)</VcpkgManifestRoot>
    <VcpkgInstalledDir>$(MSBuildThisFileDirectory)vcpkg_installed</VcpkgInstalledDir>
  </PropertyGroup>

  <ItemDefinitionGroup Condition="'$(MSBuildProjectName)'=='chafa'">
    <ClCompile>
      <ForcedIncludeFiles>$(MSBuildThisFileDirectory)msvc\chafa-config\msvc-shim.h;%(ForcedIncludeFiles)</ForcedIncludeFiles>
    </ClCompile>
  </ItemDefinitionGroup>
</Project>
